name: ADP SecureTime Automation

on:
  schedule:
  # Punch in at 11:30 AM IST (6:00 AM UTC)
  - cron: '0 6 * * 1-5'
  # OR Punch in at 12:00 PM IST (6:30 AM UTC)
  # - cron: '30 6 * * 1-5'

  # Punch out at 10:30 PM IST (5:00 PM UTC)
  - cron: '0 17 * * 1-5'
  # OR Punch out at 11:00 PM IST (5:30 PM UTC)
  # - cron: '30 17 * * 1-5'

workflow_dispatch: # Manual trigger


jobs:
  adp-punch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install puppeteer --silent
        
    - name: Run ADP automation
      env:
        ADP_USERNAME: ${{ secrets.ADP_USERNAME }}
        ADP_PASSWORD: ${{ secrets.ADP_PASSWORD }}
        PUNCH_TYPE: ${{ github.event.schedule == '0 5 * * 1-5' && 'IN' || 'OUT' }}
      run: node adp-automation.js
      
    - name: Upload debug info (only on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: debug-${{ github.run_number }}
        path: "*.png"
        retention-days: 2
